name: Update ViVi Schedules

on:
  schedule:
    # Runs Monday, Wednesday, Friday at 3 AM UTC
    - cron: '0 3 * * 1,3,5'
  workflow_dispatch: # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install axios cheerio
        
    - name: Scrape ViVi schedules
      run: node scraper.js
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add schedules.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update schedules from ViVi website" && git push)
